-- Add location and pricing snapshot fields to orders.
ALTER TABLE "Order"
ADD COLUMN "subtotalAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "gstAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "vendorShareAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "platformCommissionAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "locationSurcharge" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "cityCode" TEXT,
ADD COLUMN "areaCode" TEXT,
ADD COLUMN "areaName" TEXT,
ADD COLUMN "slotId" TEXT,
ADD COLUMN "pricingSnapshot" JSONB;

-- Add per-line resolved price snapshots.
ALTER TABLE "OrderItem"
ADD COLUMN "itemName" TEXT,
ADD COLUMN "unitPrice" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "lineSubtotal" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "lineTotal" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "gstPercent" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "gstAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "vendorShare" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "vendorShareAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "platformCommissionAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "pricingSnapshot" JSONB;
